version: '3.8'

services:
  service-1:
    build:
      context: ./backend-service
      dockerfile: Dockerfile
    ports:
      - "10300:3000"
    networks:
      internal-net:
        ipv4_address: 192.168.3.20  
    dns:
      - 192.168.3.11  
      
  service-2:
    build:
      context: ./backend-service
      dockerfile: Dockerfile
    ports:
      - "10301:3000"
    networks:
      internal-net:
        ipv4_address: 192.168.3.21
    dns:
      - 192.168.3.11  
      
  web-server-proxy:
    build:
      context: ./web-server-proxy
      dockerfile: Dockerfile
    container_name: nginx-server
    ports:
      - "10080:80"
      - "10443:443"
    restart: unless-stopped
    networks:
      internal-net:
        ipv4_address: 192.168.3.10
    dns:
      - 192.168.3.11  

  dns-server:
    build:
      context: ./dns-server
      dockerfile: Dockerfile
    container_name: bind9-server
    ports:
      - "10053:53/udp"
      - "10053:53/tcp"
    restart: unless-stopped
    networks:
      internal-net:
        ipv4_address: 192.168.3.11


networks:
  internal-net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.3.0/24