apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-web-local
  namespace: application-ns
  labels:
    app: ingress-web-local
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: backend.application.thinhlh9
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: service-backend
                port:
                  number: 5000
    - host: vault.application.thinhlh9
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: service-vault-server
                port:
                  number: 8200