---
- name: Inject Role ID and Secret ID to the 'Vault Agent'
  vars:
    vault_agent_name:         "vault-agent"
    vault_agent_secrets_path: "{{ playbook_dir }}/temp"

  block:
    - name: Write Vault Role ID to a role-id
      ansible.builtin.copy:
        content: "{{ backend_service_role_id.data.data.role_id }}"
        dest: "{{ vault_agent_secrets_path }}/role-id"
    
    - name: Write Vault Secret ID to a secret-id
      ansible.builtin.copy:
        content: "{{ backend_service_secret_id.data.data.secret_id }}"
        dest: "{{ vault_agent_secrets_path }}/secret-id"

    - name: Copy role-id to Vault Agent container
      command: "docker cp {{ vault_agent_secrets_path  }}/role-id {{ vault_agent_name }}:/vault/secrets/role-id"

    - name: Copy secret-id to Vault Agent container
      command: "docker cp {{ vault_agent_secrets_path  }}/secret-id {{ vault_agent_name }}:/vault/secrets/secret-id"

    - name: Restart Vault Agent and Backend App container
      community.docker.docker_compose_v2:
        project_src: "{{ playbook_dir }}/roles/localhost-cluster/local-project"
        services:
          - "{{ vault_agent_name }}"
          - "backend"
        state: restarted

    # - name: Restart Vault Agent container
    #   community.docker.docker_compose_v2:
    #     project_src: "{{ playbook_dir }}/roles/localhost-cluster/local-project"
    #     services:
    #       - "{{ vault_agent_name }}"
    #     state: present

