namespace: logging-ns

elasticsearch:
  image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
  replicas: 1

logstash:
  image: docker.elastic.co/logstash/logstash:8.13.0

kibana:
  image: docker.elastic.co/kibana/kibana:8.13.0

filebeat:
  image: docker.elastic.co/beats/filebeat:8.13.0
