apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Values.namespace }}
  name: filebeat-config
data:
  filebeat.yml: |
    filebeat.inputs:
    - type: container
      paths:
        - /var/log/containers/*.log

    processors:
    - add_kubernetes_metadata:
        in_cluster: true

    output.logstash:
      hosts: ["logstash:5044"]
